import { Button } from '@/components/ui/button'
import { Import } from 'lucide-react'
import { DataHandlerProps } from '@/interfaces/oc-generator/oc-generator'
import { z } from 'zod'
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useToast } from '@/components/ui/use-toast'

export const MESSAGE_ROLES = ['user', 'assistant'] as const

export const SFW_CATEGORIES = [
    'Male',
    'Female',
    'Anime',
    'Movies & TV',
    'Yandere',
    'Tsundere',
    'Gay',
    'Lesbian',
    'Non-binary',
    'Vampire',
    'OC',
    'Horror',
    'Video Games',
] as const

export const VOICE_TYPES = [
    'Male 1',
    'Male 2',
    'Male 3',
    'Male 4',
    'Male 5',
    'Male 6',
    'Female 1',
] as const

const CreateSchema = z
    .object({
        imageUri: z.string(),
        name: z.string(),
        description: z.string(),
        persona: z.string(),
        scenario: z.string(),
        exampleConversation: z.array(
            z.object({
                role: z.enum(MESSAGE_ROLES),
                content: z.string(),
            }),
        ),
        firstMessage: z.string(),
        nsfw: z.boolean(),
        voiceType: z.enum(VOICE_TYPES).optional(),
        notes: z.string().optional(),
        categories: z.array(z.enum([...SFW_CATEGORIES])),
    })
    .partial()

const CharacterNameSchema = z.object({
    name: z.string().min(1).max(32),
})

interface ImportToSakuraFMProps {
    options: {
        name: string
        locked: boolean
        currentOption: string
    }[]
}

function ImportData(options: ImportToSakuraFMProps, name: string) {
    const data = {
        name,
        description: `${name}`,
        persona: `${name}`,
        scenario: `${name}`,
        firstMessage: `${name}`,
        nsfw: false,
        notes: `Characteristics for ${name} generated by wanderer.moe's OCs generator.`,
        categories: ['OC'],
    }

    const validData = CreateSchema.safeParse(data)
    if (!validData.success) {
        console.error(validData.error)
        return
    }

    const jsonData = JSON.stringify(validData.data)

    const base64Data = btoa(jsonData)

    window.open(`https://www.sakura.fm/create?import=${base64Data}`, '_blank')
    return
}

export function ImportToSakuraFM(options: ImportToSakuraFMProps) {
    const { toast } = useToast()

    async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault()

        const formData = new FormData(e.currentTarget)

        console.log(formData)

        const validData = CharacterNameSchema.safeParse(
            Object.fromEntries(formData),
        )

        if (!validData.success) {
            console.error(validData.error)

            const errorMessage = validData.error.issues
                .map((issue) => issue.message)
                .join(', ')

            toast({
                title: 'Something went wrong',
                description: errorMessage,
            })
            return
        }

        const { name } = validData.data
        ImportData(options, name)
    }

    return (
        <Dialog>
            <DialogTrigger asChild>
                <Button
                    variant={'outline'}
                    className="flex w-full flex-row items-center gap-2">
                    <Import size={16} />
                    Import to SakuraFM
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[425px]">
                <form onSubmit={handleSubmit}>
                    <DialogHeader>
                        <DialogTitle>Import to SakuraFM</DialogTitle>
                        <DialogDescription>
                            Give your character a name and import it to
                            SakuraFM.
                        </DialogDescription>
                    </DialogHeader>
                    <div className="grid-col grid gap-2">
                        <Label htmlFor="name">Character Name</Label>
                        <Input id="name" name="name" className="w-full" />
                    </div>
                    <DialogFooter className="mt-4">
                        <Button variant="outline">Import to SakuraFM</Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    )
}
